export {default as icon01} from './icon01.svg';
export {default as icon02} from './icon02.svg';
export {default as icon03} from './icon03.svg';
export {default as icon04} from './icon04.svg';
export {default as icon05} from './icon05.svg';
export {default as icon06} from './icon06.svg';
export {default as icon07} from './icon07.svg';
export {default as icon08} from './icon08.png';
export {default as icon09} from './icon09.svg';
